### ISSUE TITLE
Remove Mixin if unneeded

### ISSUE THREAD

**Issue by moechakucha** [oupanyu/MatterOverdrive-Fabric#2]
[The same](https://github.com/Archasmiel/fabric_thaumcraft-rewrited/issues/2) again...
Mixin is not **required** and can be removed if you don't need to inject code into existing classes.

**Comment by htrskmiku** [comment]
okay.Thank you!

**Comment by htrskmiku** [comment]
Now it has been removed.Sorry to fix it too late because of an examination.
